function build_toml_mex()
    clear all;clc;
        %% parse string
        mex('toml_parse_string.cpp', ...
        '-I"C:\Git_Repo\TOML_MatlabMex\tomlplusplus\include"', ...
        'CXXFLAGS="$CXXFLAGS -std=c++17"');

        %% write string
        mex('toml_write_string.cpp', ...
        '-I"C:\Git_Repo\TOML_MatlabMex\tomlplusplus\include"', ...
        'CXXFLAGS="$CXXFLAGS -std=c++17"');

        %% parse file
        mex('toml_parse_file.cpp', ...
        '-I"C:\Git_Repo\TOML_MatlabMex\tomlplusplus\include"', ...
        'CXXFLAGS="$CXXFLAGS -std=c++17"');
end
