function build_toml_mex()
    clear all
        mex('toml_write_string.cpp', ...
        '-I"C:\Git_Repo\TOML_MatlabMex\tomlplusplus\include"', ...
        'CXXFLAGS="$CXXFLAGS -std=c++17"');

        mex('toml_parse_file.cpp', ...
        '-I"C:\Git_Repo\TOML_MatlabMex\tomlplusplus\include"', ...
        'CXXFLAGS="$CXXFLAGS -std=c++17"');
end
